import type { RecommendationWine } from "./types";

export const MOCK_WINES: RecommendationWine[] = [
  {
    id: "w1",
    name: "Hidden Bench Estate Pinot Noir",
    producer: "Hidden Bench",
    type: "Red",
    varietal: "Pinot Noir",
    country: "Canada",
    subRegion: "Niagara",
    region: "Niagara, Ontario",
    price: 29.95,
    rating: 4.2,
    ratingCount: 540,
    ratingSource: "direct",
    matchScore: 4.4,
    stockConfidence: "High",
    why: ["Silky and fruit-forward profile", "Great with pasta and roast dishes", "In stock 2.1 km away"],
    storeId: "queen-west",
    storeLabel: "LCBO - Queen St W",
    lcboUrl: "https://www.lcbo.com/en/catalogsearch/result/?q=%22Hidden%20Bench%20Estate%20Pinot%20Noir%22",
    lcboLinkType: "search_fallback",
    vivinoUrl: "https://www.vivino.com/search/wines?q=hidden%20bench%20estate%20pinot%20noir",
  },
  {
    id: "w2",
    name: "Tawse Growers Blend Chardonnay",
    producer: "Tawse",
    type: "White",
    varietal: "Chardonnay",
    country: "Canada",
    subRegion: "Niagara",
    region: "Niagara, Ontario",
    price: 24.95,
    rating: 4.1,
    ratingCount: 710,
    ratingSource: "direct",
    matchScore: 4.1,
    stockConfidence: "High",
    why: ["Crisp acidity with citrus finish", "Great value in your selected range", "In stock 1.4 km away"],
    storeId: "king-west",
    storeLabel: "LCBO - King St",
    lcboUrl: "https://www.lcbo.com/en/catalogsearch/result/?q=%22Tawse%20Growers%20Blend%20Chardonnay%22",
    lcboLinkType: "search_fallback",
    vivinoUrl: "https://www.vivino.com/search/wines?q=tawse%20growers%20blend%20chardonnay",
  },
  {
    id: "w3",
    name: "Bisol Jeio Prosecco Brut",
    producer: "Bisol",
    type: "Bubbly",
    varietal: "Prosecco",
    country: "Italy",
    subRegion: "Veneto",
    region: "Veneto, Italy",
    price: 21.95,
    rating: 4.0,
    ratingCount: 1200,
    ratingSource: "direct",
    matchScore: 3.8,
    stockConfidence: "Medium",
    why: ["Fresh bubbly option for tonight", "Popular social pick with strong reviews", "Limited stock 3.3 km away"],
    storeId: "dundas-west",
    storeLabel: "LCBO - Dundas St W",
    lcboUrl: "https://www.lcbo.com/en/catalogsearch/result/?q=%22Bisol%20Jeio%20Prosecco%20Brut%22",
    lcboLinkType: "search_fallback",
    vivinoUrl: "https://www.vivino.com/search/wines?q=bisol%20jeio%20prosecco%20brut",
  },
  {
    id: "w4",
    name: "Cloudy Bay Sauvignon Blanc",
    producer: "Cloudy Bay",
    type: "White",
    varietal: "Sauvignon Blanc",
    country: "New Zealand",
    subRegion: "Marlborough",
    region: "Marlborough, New Zealand",
    price: 34.95,
    rating: 4.3,
    ratingCount: 1900,
    ratingSource: "direct",
    matchScore: 4.5,
    stockConfidence: "High",
    why: ["High-rated white with bright citrus", "Strong Vivino performance", "Available in your selected store"],
    storeId: "king-west",
    storeLabel: "LCBO - King St",
    lcboUrl: "https://www.lcbo.com/en/cloudy-bay-sauvignon-blanc-304469",
    lcboLinkType: "verified_product",
    vivinoUrl: "https://www.vivino.com/search/wines?q=cloudy%20bay%20sauvignon%20blanc",
  },
  {
    id: "w5",
    name: "Antinori Peppoli Chianti Classico",
    producer: "Antinori",
    type: "Red",
    varietal: "Sangiovese",
    country: "Italy",
    subRegion: "Tuscany",
    region: "Tuscany, Italy",
    price: 31.95,
    rating: 4.1,
    ratingCount: 2600,
    ratingSource: "producer_avg",
    matchScore: 4.0,
    stockConfidence: "Medium",
    why: ["Classic Tuscan profile", "Reliable highly rated producer", "Limited stock but still available"],
    storeId: "queen-west",
    storeLabel: "LCBO - Queen St W",
    lcboUrl: "https://www.lcbo.com/en/catalogsearch/result/?q=%22Antinori%20Peppoli%20Chianti%20Classico%22",
    lcboLinkType: "search_fallback",
    vivinoUrl: "https://www.vivino.com/search/wines?q=antinori%20peppoli%20chianti%20classico",
  },
  {
    id: "w6",
    name: "Louis Jadot Chablis",
    producer: "Louis Jadot",
    type: "White",
    varietal: "Chardonnay",
    country: "France",
    subRegion: "Chablis",
    region: "Chablis, Burgundy, France",
    price: 38.95,
    rating: 4.2,
    ratingCount: 1330,
    ratingSource: "direct",
    matchScore: 4.3,
    stockConfidence: "High",
    why: ["Classic cool-climate Chardonnay", "Top-rated and balanced", "Reliable in-stock inventory"],
    storeId: "king-west",
    storeLabel: "LCBO - King St",
    lcboUrl: "https://www.lcbo.com/en/catalogsearch/result/?q=%22Louis%20Jadot%20Chablis%22",
    lcboLinkType: "search_fallback",
    vivinoUrl: "https://www.vivino.com/search/wines?q=louis%20jadot%20chablis",
  },
  {
    id: "w7",
    name: "Kim Crawford Sauvignon Blanc",
    producer: "Kim Crawford",
    type: "White",
    varietal: "Sauvignon Blanc",
    country: "New Zealand",
    subRegion: "Marlborough",
    region: "Marlborough, New Zealand",
    price: 21.95,
    rating: 4.0,
    ratingCount: 4100,
    ratingSource: "direct",
    matchScore: 4.0,
    stockConfidence: "High",
    why: ["Easy crowd-pleaser", "Very strong review volume", "Great value for weekday or hosting"],
    storeId: "queen-west",
    storeLabel: "LCBO - Queen St W",
    lcboUrl: "https://www.lcbo.com/en/catalogsearch/result/?q=%22Kim%20Crawford%20Sauvignon%20Blanc%22",
    lcboLinkType: "search_fallback",
    vivinoUrl: "https://www.vivino.com/search/wines?q=kim%20crawford%20sauvignon%20blanc",
  },
  {
    id: "w8",
    name: "Cakebread Cellars Chardonnay",
    producer: "Cakebread Cellars",
    type: "White",
    varietal: "Chardonnay",
    country: "USA",
    subRegion: "Napa Valley",
    region: "Napa Valley, California",
    price: 64.95,
    rating: 4.4,
    ratingCount: 980,
    ratingSource: "none",
    matchScore: 4.6,
    stockConfidence: "Medium",
    why: ["Premium Napa benchmark", "Very high user satisfaction", "Great special-occasion bottle"],
    storeId: "dundas-west",
    storeLabel: "LCBO - Dundas St W",
    lcboUrl: "https://www.lcbo.com/en/catalogsearch/result/?q=%22Cakebread%20Cellars%20Chardonnay%22",
    lcboLinkType: "search_fallback",
    vivinoUrl: "https://www.vivino.com/search/wines?q=cakebread%20cellars%20chardonnay",
  },
  {
    id: "w9",
    name: "Dr. Loosen Blue Slate Riesling",
    producer: "Dr. Loosen",
    type: "White",
    varietal: "Riesling",
    country: "Germany",
    subRegion: "Mosel",
    region: "Mosel, Germany",
    price: 27.95,
    rating: 4.1,
    ratingCount: 860,
    ratingSource: "direct",
    matchScore: 4.1,
    stockConfidence: "High",
    why: ["Bright and mineral style", "Excellent quality-to-price", "Good option if you want lower alcohol"],
    storeId: "king-west",
    storeLabel: "LCBO - King St",
    lcboUrl: "https://www.lcbo.com/en/catalogsearch/result/?q=%22Dr.%20Loosen%20Blue%20Slate%20Riesling%22",
    lcboLinkType: "search_fallback",
    vivinoUrl: "https://www.vivino.com/search/wines?q=dr.%20loosen%20blue%20slate%20riesling",
  },
  {
    id: "w10",
    name: "Domaine Bousquet Rose",
    producer: "Domaine Bousquet",
    type: "Rose",
    varietal: "Provence Rose",
    country: "Argentina",
    subRegion: "Mendoza",
    region: "Mendoza, Argentina",
    price: 19.95,
    rating: 4.0,
    ratingCount: 720,
    ratingSource: "direct",
    matchScore: 3.9,
    stockConfidence: "High",
    why: ["Fresh and easy-drinking", "Affordable and reliable", "Great for social occasions"],
    storeId: "queen-west",
    storeLabel: "LCBO - Queen St W",
    lcboUrl: "https://www.lcbo.com/en/catalogsearch/result/?q=%22Domaine%20Bousquet%20Rose%22",
    lcboLinkType: "search_fallback",
    vivinoUrl: "https://www.vivino.com/search/wines?q=domaine%20bousquet%20rose",
  },
];
